version: "3.7"

services:
  345securitymqtt:
    image: registry.gitlab.com/vondruska/345securitymqtt:latest
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    env_file: mqtt.env
    restart: unless-stopped

  mosuqitto:
    image: eclipse-mosquitto
    volumes:
      - "/opt/mosquitto/config:/mosquitto/config"
      - "/mosquitto/data"
      - "/mosquitto/log"
    ports:
      - "9001:9001"
      - "1883:1883"
    restart: unless-stopped


  homeassistant:
    image: homeassistant/raspberrypi3-homeassistant:0.93.1
    devices:
      - "/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave"
    network_mode: "host"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/homeassistant:/config"
    restart: unless-stopped
