version: "3.7"

services:
  345securitymqtt:
    image: vondruska/345securitymqtt:latest
    devices:
      - "/dev/bus/usb:/dev/bus/usb"
    env_file: mqtt.env
    restart: unless-stopped

  mosuqitto:
    image: eclipse-mosquitto
    volumes:
      - "/opt/mosquitto/config:/mosquitto/config"
      - "/mosquitto/data"
      - "/mosquitto/log"
    ports:
      - "9001:9001"
      - "1883:1883"
    restart: unless-stopped

  homeassistant:
    image: homeassistant/home-assistant:0.106.2
    devices:
      - "/dev/serial/by-id/usb-0658_0200-if00:/dev/zwave"
    network_mode: "host"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/homeassistant:/config"
    restart: unless-stopped

  nodered:
    image: nodered/node-red:latest
    environment:
      - TZ=US/Eastern
    volumes:
      - "/opt/nodered:/data"
    ports:
      - "1880:1880"
    user: "1000:1000"
    restart: unless-stopped

  webhook-pull:
    image: vondruska/webhook-script-runner
    environment:
      TOKEN:
      SCRIPT_EXECUTION_TIMEOUT: 10000
      STARTUP_SCRIPT: "/scripts/startup.sh"
      WEBHOOK_SCRIPT: "/scripts/hook.sh"
      GIT_PASSWORD:
      GIT_USERNAME:
      GIT_HOST: "github.com"
      HOME_ASSISTANT_URL:
    ports:
      - "9080:9080"
    volumes:
      - ./scripts:/scripts
      - /opt/homeassistant:/homeassistant
    user: "1001:1001"
    restart: unless-stopped

  nut:
    image: vondruska/nut-upsd
    restart: unless-stopped
    ports:
      - "3493:3493"
    devices:
      - "/dev/bus/usb:/dev/bus/usb"

  
